### ISSUE TITLE
Building failure

### ISSUE THREAD

**Issue by richardlalancette** [flyover/imgui-js#12]
(master) ~/youidev/imgui-js $ make
npm run start-example-node

> imgui-js@1.0.0 start-example-node /Users/developer/youidev/imgui-js
> node example/index.js

Total allocated space (uordblks) @ _init: 6528
ReferenceError: HTMLCanvasElement is not defined
    at Object.Init (file:///Users/developer/youidev/imgui-js/example/imgui_impl.js:177:31)
    at file:///Users/developer/youidev/imgui-js/example/main.js:88:28
    at Generator.next (<anonymous>)
    at fulfilled (file:///Users/developer/youidev/imgui-js/example/main.js:5:62)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)

**Comment by flyover** [comment]
Thanks for reporting this; it should be fixed with 5a5674e590439b6c49ecae9aa24a319ed0ae8d86.

**Comment by richardlalancette** [comment]
Worked beautifully!
Thank you!

**Comment by richardlalancetteyoui** [comment]
Can be closed.
